### ISSUE TITLE
Doesn't support karma 4

### ISSUE THREAD

**Issue by kaiyoma** [JamieMason/karma-benchmark#19]
If I try to upgrade to karma 4, `yarn check` fails with this error:

```
error "karma-benchmark#karma@^3.1.4" doesn't satisfy found match of "karma@4.0.1"
```

**Comment by JamieMason** [comment]
karma-benchmark was last updated when karma v3 was the latest version. A PR would be needed that updates karma-benchmark and fixes any breaking changes that might have been introduced in karma v4.

Thanks a lot Kyle.

**Comment by kaiyoma** [comment]
Is this fixed now? I just noticed that karma-benchmark is once again a version behind karma:

```
karma-benchmark@1.0.4" has incorrect peer dependency "karma@^4.2.0".
```

The above error can be seen during `yarn install` if you install the latest version of karma-benchmark (1.0.4) with the latest version of karma (5.0.2).
