### ISSUE TITLE
Add the ability to skip suites and benchmarks

### ISSUE THREAD

**Issue by lazd** [JamieMason/karma-benchmark#4]
It would be useful if certain suites or benchmarks could be skipped. One way to do this is to add a `.skip()` method to the `benchmark` and `suite` functions a la [inclusive tests in Mocha](http://visionmedia.github.io/mocha/#inclusive-tests):

```js
suite.skip('Set value', function() {
  // ...
});

suite('Get value', function() {
  benchmark.skip(function() {
    // ...
  });
});
```

This is useful when benchmarks are crashing and you need to avoid running them.

**Comment by JamieMason** [comment]
This landed in 0.6.0, thanks @lazd.
