### ISSUE TITLE
Add the ability to run only a single suite or benchmark

### ISSUE THREAD

**Issue by lazd** [JamieMason/karma-benchmark#5]
Similar to #4, it would be useful to allow running only a single suite or benchmark a la [exclusive tests in Mocha](http://visionmedia.github.io/mocha/#exclusive-tests).

```js
suite.only('Set value', function() {
  // ...
});
```

Or:

```js
suite('Get value', function() {
  benchmark.only(function() {
    // ...
  });
});
```

This is useful when tuning a single benchmark.

**Comment by JamieMason** [comment]
This landed in 0.6.0, thanks @lazd.
